VNX: raise exception if no storops
Previously, if storops is not installed, driver will raise
AttributeError: 'NoneType' object has no attribute 'VNXSystem'.
Now, driver will report clear message in order not to confuse user.

Closes-Bug: 1629223
Change-Id: I1fbdd73063f3d06329f94184701014b247fb889e
(cherry picked from commit a87d978a4635f4c4b1e04fd82d2c9b154f88975d)